export const REGISTRATION_USER = 'REGISTRATION_USER';
export const POST_REGISTRATION_USER = 'POST_REGISTRATION_USER';

export const AUTHORIZATION_USER = 'AUTHORIZATION_USER';
export const POST_AUTHORIZATION_USER = 'POST_AUTHORIZATION_USER';

export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';

export const LOGOUT_USER = 'LOGOUT_USER';
export const DELETE_USER = 'DELETE_USER';