export const CREATE_QUESTION = 'CREATE_QUESTION';
export const SET_QUESTION = 'SET_QUESTION';

export const EDIT_QUESTION = 'EDIT_QUESTION';
export const EDIT_QUESTION_BY_ID = 'EDIT_QUESTION_BY_ID';

export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_BY_ID = 'DELETE_QUESTION_BY_ID';

export const CREATE_ANSWER = 'CREATE_ANSWER';
export const SET_ANSWER = 'SET_ANSWER';

export const EDIT_ANSWER = 'EDIT_ANSWER';
export const EDIT_ANSWER_BY_ID = 'EDIT_ANSWER_BY_ID';

export const DELETE_ANSWER = 'DELETE_ANSWER';
export const DELETE_ANSWER_BY_ID = 'DELETE_ANSWER_BY_ID';

export const MOVING_ANSWER = 'MOVING_ANSWER';
export const MOVING_ANSWER_BY_ID = 'MOVING_ANSWER_BY_ID';

export const CLEAR_ANSWERS = 'CLEAR_ANSWERS';